dist: xenial
language: python
python:
  - "3.6"

# Pre-installed packages.
# shellcheck v0.5.0
# Refer to the following link to install specific version shellcheck binary.
# https://github.com/koalaman/shellcheck#installing-the-shellcheck-binary
# php 7.2
install:
  - pip install pyyaml pycodestyle python-magic

env:
  - SCRIPT="./sanity-check.sh"
  - SCRIPT="docker run -v $(pwd):/test-definitions --workdir /test-definitions fsfe/reuse lint"

script:
  - $SCRIPT
