site_name: Test Definitions
site_url: https://readthedocs.org/test-definitions
repo_url: https://github.com/linaro/test-definitions
copyright: Linaro Ltd.
extra_css: [extra.css]
theme:
    name: material
plugins:
    - linaro-test-definitions:
        table_dirs:
            - 'automated/linux'
            - 'automated/android'
            - 'manual'
    - tags
    - exclude:
        glob:
          - plans/*
